### PR TITLE
Supersede `gbif_species_name_match` function

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR supersedes the inborutils function `gbif_species_name_match`, see #120. I decided to not deprecate our function based on [life cycle documentation](https://lifecycle.r-lib.org/articles/stages.html#superseded).

I also converted the documentation of this function to Markdown syntax for better rendering.

While building documentation (via `devtools::document()`) I also improved the Rd documentation of `download_knmi_data_hour.Rd`. I think the very last changes were not built.

### CODE REVIEW

**Comment by hansvancalster** [comment]
@damianooldoni I've changed the base branch from main to v0.3.0 in which I started using checklist package. The v0.3.0 is still a work in progress. Can you have a look at the conflicts?

**Comment by damianooldoni** [comment]
Thanks @hansvancalster. I have just done it. Waiting for automatic checks now...

**Comment by hansvancalster** [comment]
Thanks @damianooldoni! Don't worry about the failing check - I will deal with this in v0.3.0 branch.

**Review by hansvancalster — APPROVED** [review]

**Comment by damianooldoni** [comment]
Thanks @hansvancalster. FYI: the failure is due to a problem while installing the `units` package, which is a dependency of `sf`.

**Pull request merged**
