### PR TITLE
Change maintainer See #58

### PR DESCRIPTION
**Pull request by hansvancalster**

### CODE REVIEW

**Comment by peterdesmet** [comment]
While updating the maintainer, I also had a look at all contributors and updated their roles based on the [commits on GitHub](https://github.com/inbo/inborutils/graphs/contributors). It's not a perfect metric, but it gives an indication on the contribution.

We now have 3 authors (those with more than 30 commits)

- @hansvancalster: from ctb to aut + also maintainer
- @stijnvanhoey: remains aut
- @damianooldoni: from ctb to aut

And 6 contributors (alphabetically):

- @DimEvil: added
- @peterdesmet: unchanged
- @Fhuysent: unchanged
- @ThierryO: from aut to ctb
- @florisvdh: added
- @pietervsd: from aut to ctb

Any objections?

For PR from new authors, I would try to add them as contributors

**Review by florisvdh — APPROVED** [review]
@peterdesmet I follow your approach.

Considering the re-aligning of authors in `DESCRIPTION` (one line per person), I assume you prefer this layout to make it more readable when a user consults the package description? It is not tidyverse-styled, but the description as consulted by a user is awkward anyway. ;-)

Considering the latter, you can in fact make an extra file in the R folder so that one can consult a nicer description by typing `?inborutils` (after loading the package) or `package?inborutils`. [Here](https://github.com/inbo/watina/blob/a4b8fcce270e632b0059a050964645808fc0be15/R/watina.R) is an example. (But don't add the `globalVariables()` function)

**Comment by peterdesmet** [comment]
The one line per authors is indeed for easier reading. It's also written as such in http://r-pkgs.had.co.nz/description.html#author

Note that an easier overview of the authors is already available at https://inbo.github.io/inborutils/authors.html, but I've added a inborutils.R file so users can do `?inborutils`. Thanks for the suggestion.

**Review by peterdesmet — APPROVED** [review]

**Comment by peterdesmet** [comment]
Updated page: https://inbo.github.io/inborutils/authors.html

**Pull request merged**
