### PR TITLE
add dframe factor to char function

### PR DESCRIPTION
**Pull request by stijnvanhoey**
add function to convert factors to chars within dframe (credits to Thierry)

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
@ThierryO  ok to merge?

**Comment by ThierryO** [comment]
I'd add the following to the Roxygen2 header

    #' @importFrom dplyr %>% mutate_each_ funs

It alerts the user that the `dplyr` package is required. And add the required import directives in case you want to add the function to a package.

**Review by ThierryO — CHANGES_REQUESTED** [review]
I'd add the following to the Roxygen2 header

```
#' @importFrom dplyr %>% mutate_each_ funs
```

It alerts the user that the `dplyr` package is required. And add the required import directives in case you want to add the function to a package.

**Comment by stijnvanhoey** [comment]
Great advice, thanks!

**Pull request merged**
