### PR TITLE
Patch zenodo download

### PR DESCRIPTION
**Pull request by hansvancalster**
Fixes a bug reported by @damianooldoni

### CODE REVIEW

**Review by damianooldoni — APPROVED** [review]
Nice, Hans! Thanks.

**Review by florisvdh — CHANGES_REQUESTED** [review]
Thanks @hansvancalster. Looks good. I've been testing some examples. Most of them work.

This one (from the examples) is still broken though:

```r
> download_zenodo(doi = "10.5281/zenodo.1283345")
Will download 1 file (total size: 821 KiB) from https://doi.org/10.5281/zenodo.1283345 (niche_vlaanderen 1.0; version: 1.0)

Error in (function (url, destfile, quiet = TRUE, mode = "wb", handle = new_handle())  : 
  Failed to open file ./inbo/niche_vlaanderen-1.0.zip.curltmp.
```

Maybe the Zenodo 'filename' contains the `inbo/` part which makes this not work anymore. Anyhow all examples worked before, so I presume that all problems addressed here are ultimately because of the changes in the Zenodo website.

**Comment by hansvancalster** [comment]
> Maybe the Zenodo 'filename' contains the `inbo/` part which makes this not work anymore. Anyhow all examples worked before, so I presume that all problems addressed here are ultimately because of the changes in the Zenodo website.

That was the problem indeed. Fixed in [a553b23](https://github.com/inbo/inborutils/pull/123/commits/a553b23697bb435bbde6c6a397efb47982ea66b1)

**Review by florisvdh — APPROVED** [review]
Well done :tada: 

```r
> download_zenodo(doi = "10.5281/zenodo.1283345")
Will download 1 file (total size: 821 KiB) from https://doi.org/10.5281/zenodo.1283345 (niche_vlaanderen 1.0; version: 1.0)

 [100%] Downloaded 840728 bytes...

Verifying file integrity...

niche_vlaanderen-1.0.zip was downloaded and its integrity verified (md5sum: 695b724cc4345f49655a0b861b3ece9d)
```

**Pull request merged**
