### PR TITLE
deprecate functions that are moved to inbodb

### PR DESCRIPTION
**Pull request by ElsLommelen**
Deprecation of functions that are moved tot new package inbodb:
- using function gives warning
- asking for documentation refers to list of deprecated functions with replacing functions (but original documentation is still accessible)

### CODE REVIEW

**Review by ThierryO — APPROVED** [review]

**Review by hansvancalster — APPROVED** [review]

**Comment by hansvancalster** [comment]
@ElsLommelen can you also change the version number to 0.1.0.9081

I don't know a solution to the failed travis checks either. The error is:
ERROR: dependency ‘rmarkdown’ is not available for package ‘pkgdown’ * removing ‘/home/travis/R/Library/pkgdown’

**Comment by florisvdh** [comment]
The travis error seems to sit [here](https://travis-ci.com/github/inbo/inborutils/builds/162364071#L2413). I.e. `htmltools` cannot be installed because `package ‘Rcpp’ was installed before R 4.0.0: please re-install it`.
htmltools > rmarkdown > pkgdown.

Maybe the problem is in htmltools itself; the setup on Travis [uses](https://travis-ci.com/github/inbo/inborutils/builds/162364071#L1181) R 3.6.3.

Didn't yet find the actual problem though.

**Comment by florisvdh** [comment]
But [here](https://travis-ci.community/t/package-build-failure-on-r-devel-some-packages-need-to-be-reinstalled-using-r-4-0-0/8070) is a clue.

**Comment by florisvdh** [comment]
I see no [caches for inborutils](https://travis-ci.com/github/inbo/inborutils/caches) however; don't know whether they are user-specific though. Maybe @peterdesmet can help here.

Docs on clearing caches are [here](https://docs.travis-ci.com/user/caching#clearing-caches).

It appears that R 4.0.0 is first installed [here](https://travis-ci.com/github/inbo/inborutils/builds/162364071#L697), and [later](https://travis-ci.com/github/inbo/inborutils/builds/162364071#L1162) R 3.6.3 is installed because it's a dependency of `r-cran-rgdal` (precompiled ubuntu package). Therein may lie the problem.

**Comment by ElsLommelen** [comment]
Apparently it is defined in the yaml file, I tried removing it.

**Comment by ElsLommelen** [comment]
nope, maybe @ThierryO 's suggestions to wait some days till updates to R 4.0.0 are settled in all dependency packages is one of the easiest solutions?
(What I don't understand: 'R package cache' caches packages from the local library, but I am working on a Windows machine.  On a Linux machine I often have to install additional features to make packages run (e.g. gdal), where does Travis get these features on my Windows machine?)

**Comment by ThierryO** [comment]
R 4.0.0 was rolled out just a few days ago. So it hasn't propagated to all repositories. Hence my suggestion to way a couple days or weeks untill it has propagated. This PR doesn't seem to be very urgent.

**Comment by florisvdh** [comment]
> where does Travis get these features on my Windows machine

@ElsLommelen I guess it doesn't because Travis does its work in Linux by default (optionally Mac). In the cloud. The [docs for R](https://docs.travis-ci.com/user/languages/r/) seem a bit outdated however (currently Ubuntu Xenial is being used).

I guess problem solving will depend on the Travis R build that will have to migrate from current PPA https://launchpad.net/~marutter/+archive/ubuntu/c2d4u3.5 (for downloading `r-cran-rgdal` and its dependencies, incl R) to a new (yet not existing?) PPA with precompiled packages for R 4.0.0.

**Comment by florisvdh** [comment]
I got the same problem with `n2khab` package ([errored build](https://travis-ci.com/github/inbo/n2khab/builds/162447555)).

If you like to fix the travis build (in R `4.0.0`), it suffices to drop the binary `rgdal` package specification from `.travis.yml` (see inbo/n2khab@3ab00b1), which invokes the installation of precompiled `r-cran-rgdal` and hence its dependencies from marutter's R 3.5 PPA, overwriting R `4.0.0` with R `3.6.3` (noted [above](https://github.com/inbo/inborutils/pull/81#issuecomment-620436622)).

The first [new build](https://travis-ci.com/github/inbo/n2khab/builds/162455091) took approx. 40 minutes (compilation of all packages, including `rgdal`, in R `4.0.0`), but I assume that the cache on Travis will make this more efficient in later builds. At least it is clear that many more R packages were actively compiled and installed, compared to earlier succesful builds on R `3.6.2` ([example](https://travis-ci.com/github/inbo/n2khab/builds/162172322) from yesterday). I assume this large bulk compilation will happen just once (per R version), we'll see.

**Comment by ElsLommelen** [comment]
Thanks @florisvdh !

**Comment by florisvdh** [comment]
FYI I can add that next `n2khab` Travis builds are indeed much faster, roughly 5 minutes instead of 40. Only one package needed to be [installed](https://travis-ci.com/github/inbo/n2khab/builds/162743936#L1238) because of an update on CRAN, apart from the explicitly specified installations of `pkgdown` and `inborutils`.

**Pull request merged**
