### PR TITLE
connect_inbo_dbase(): on unix OS, select latest driver version

### PR DESCRIPTION
**Pull request by florisvdh**
When multiple driver versions are installed for MS SQL server, the latest version will be automatically selected.

Is linked to some [earlier](https://github.com/inbo/inborutils/pull/48#issuecomment-494725779) discussion on this.

@peterdesmet I understood that `connect_inbo_dbase()` did not function on Mac? Can you report your output of `odbc::odbcListDrivers()` ? Maybe we can solve it here as well.

### CODE REVIEW

**Comment by peterdesmet** [comment]
Sorry, saw this quite late. Here's the output:

```
> odbc::odbcListDrivers()
                           name   attribute
1             PostgreSQL Driver      Driver
2                 SQLite Driver      Driver
3 ODBC Driver 13 for SQL Server Description
4 ODBC Driver 13 for SQL Server      Driver
5 ODBC Driver 13 for SQL Server  UsageCount
6 ODBC Driver 17 for SQL Server Description
7 ODBC Driver 17 for SQL Server      Driver
8 ODBC Driver 17 for SQL Server  UsageCount
                                    value
1             /usr/local/lib/psqlodbcw.so
2     /usr/local/lib/libsqlite3odbc.dylib
3 Microsoft ODBC Driver 13 for SQL Server
4    /usr/local/lib/libmsodbcsql.13.dylib
5                                       2
6 Microsoft ODBC Driver 17 for SQL Server
7    /usr/local/lib/libmsodbcsql.17.dylib
8                                       1
```

**Comment by florisvdh** [comment]
OK, and does `.Platform$OS.type == "unix"` return `TRUE`?

**Comment by peterdesmet** [comment]
Yes:

```
> .Platform$OS.type == "unix"
[1] TRUE
```

**Comment by florisvdh** [comment]
So does this work:

```r
conn <- dbConnect(odbc(),
                      driver = "ODBC Driver 17 for SQL Server",
                      server = "inbo-sql08-prd.inbo.be",
                      port = 1433,
                      database = "W0002_00_Watina",
                      trusted_connection = "YES")
```
If not, can you tweak the above arguments to make it work?

In case it works, I expect `connect_inbo_dbase("W0002_00_Watina")` to work as well (from the current branch but probably also from master).

**Comment by peterdesmet** [comment]
I can only make it work as:

```r
con <- DBI::dbConnect(
   odbc::odbc(),
   driver = "ODBC Driver 17 for SQL Server",
   server = "inbo-sql08-prd.inbo.be",
   port = 1433,
   database = "W0003_00_Lims", # Not for W0002_00_Watina
   uid = "uid created for coding club",
   pwd = "uid created for coding club"
)
```

**Comment by florisvdh** [comment]
@peterdesmet will solve Kerberos at his side later. @ThierryO can you test functionality in Linux. Here it is all good. Somebody has to approve ;-)

**Comment by florisvdh** [comment]
@ElsLommelen can you check whether the updates in `connect_inbo_dbase()` in this branch work for you, and if so, approve and merge? It's better to have this included when considering isolation of `connect_inbo_dbase()`.

I'm quite sure it will just work - this long-standing PR is only to make sure that on Linux / Mac setups with multiple SQL Server drivers, the latest one is selected (still assuming a Kerberos authentication just as before). I already tested that myself.

Note: checks just fail because of current failed checks in master, see #74 .

**Review by ElsLommelen — APPROVED** [review]

**Pull request merged**
