### PR TITLE
inboveg_recordings.Rd: use UTF-8 encoding

### PR DESCRIPTION
**Pull request by florisvdh**

### CODE REVIEW

**Review by ThierryO — DISMISSED** [review]
You should only use ASCII characters in R packages. Replace `é` with the ASCII equivalent `\u00e9`. Try `cat("\u00e9")` and you'll get `é`.

**Comment by florisvdh** [comment]
what I did was just `devtools::document()`, and this popped up as a change.

Do you suggest to actually code as:

`# get the relev\u00e9s from one survey and collect the data`

**Comment by ThierryO** [comment]
Yes. Other options are writting it a `releves` or find a synonym. @hansvancalster @ElsDeBie

**Comment by florisvdh** [comment]
It appears that 'relevé' is spelled as such in scientific work. I'll push an extra commit, thanks for the help.

**Comment by hansvancalster** [comment]
records could be a synonym, but spelling it as relev\u00e9s is fine also

**Comment by florisvdh** [comment]
@ThierryO I found this actually doesn't work. Haven't pushed it. This would be the diff:

```diff
diff --git a/R/inboveg_recordings.R b/R/inboveg_recordings.R
index 7b8c322..8be13f6 100644
--- a/R/inboveg_recordings.R
+++ b/R/inboveg_recordings.R
@@ -36,7 +36,7 @@
 #' \dontrun{
 #' con <- connect_inbo_dbase("D0010_00_Cydonia")
 #'
-#' # get the relevés from one survey and collect the data
+#' # get the relev\u00e9s from one survey and collect the data
 #' recording_heischraal2012 <- inboveg_recordings(con, survey_name =
 #' "MILKLIM_Heischraal2012", collect = TRUE)
 #'
@@ -49,7 +49,7 @@
 #' c("MILKLIM_Heischraal2012", "NICHE Vlaanderen"), multiple = TRUE,
 #' collect = TRUE)
 #'
-#' # get all relevés of all surveys,  don't collect the data
+#' # get all relev\u00e9s of all surveys,  don't collect the data
 #' allrecordings <- inboveg_recordings(con)
 #'
 #' # Close the connection when done
diff --git a/man/inboveg_recordings.Rd b/man/inboveg_recordings.Rd
index 222aaff..755a094 100644
--- a/man/inboveg_recordings.Rd
+++ b/man/inboveg_recordings.Rd
@@ -42,7 +42,7 @@ vegetation layers with which cover) for one or more surveys.
 \dontrun{
 con <- connect_inbo_dbase("D0010_00_Cydonia")
 
-# get the relevés from one survey and collect the data
+# get the relev\\u00e9s from one survey and collect the data
 recording_heischraal2012 <- inboveg_recordings(con, survey_name =
 "MILKLIM_Heischraal2012", collect = TRUE)
 
@@ -55,7 +55,7 @@ recording_severalsurveys <- inboveg_recordings(con, survey_name =
 c("MILKLIM_Heischraal2012", "NICHE Vlaanderen"), multiple = TRUE,
 collect = TRUE)
 
-# get all relevés of all surveys,  don't collect the data
+# get all relev\\u00e9s of all surveys,  don't collect the data
 allrecordings <- inboveg_recordings(con)
```

In the html help you then get:

```
## Not run: 
con <- connect_inbo_dbase("D0010_00_Cydonia")

# get the relev\u00e9s from one survey and collect the data
recording_heischraal2012 <- inboveg_recordings(con, survey_name =
"MILKLIM_Heischraal2012", collect = TRUE)

# get all recordings from MILKLIM surveys (partial matching), don't collect
recording_milkim <- inboveg_recordings(con, survey_name = "%MILKLIM%",
collect = TRUE)

# get recordings from several specific surveys
recording_severalsurveys <- inboveg_recordings(con, survey_name =
c("MILKLIM_Heischraal2012", "NICHE Vlaanderen"), multiple = TRUE,
collect = TRUE)

# get all relev\u00e9s of all surveys,  don't collect the data
allrecordings <- inboveg_recordings(con)

# Close the connection when done
dbDisconnect(con)
rm(con)

## End(Not run)
```

With current state of the branch, all should work fine.

**Review by hansvancalster — APPROVED** [review]
Good catch. Thanks!

**Pull request merged**
