### PR TITLE
Inboveg header

### PR DESCRIPTION
**Pull request by hansvancalster**
Also return date related header information.

### CODE REVIEW

**Review by ElsDeBie — APPROVED** [review]
An Leyssen also noticed this and asked to update. Thanks Hans!

**Comment by hansvancalster** [comment]
@peterdesmet @damianooldoni I think something went wrong with the deployment of the gh-pages site after merging this branch to master: [see here](https://travis-ci.org/inbo/inborutils/builds/651547194?utm_medium=notification&utm_source=github_status
).

Can one of you have a look. I tried triggering a rebuild, but I may not have the rights to do so? In any case, I didn't found the button to restart a build.

**Comment by damianooldoni** [comment]
Ah, probably due to the settings for Travis CI? 
Logged in as Stijn Van Hoey...

**Comment by peterdesmet** [comment]
Will check

**Pull request merged**
