### PR TITLE
Add GitHub actions for tests and building site

### PR DESCRIPTION
**Pull request by damianooldoni**
This PR adds two workflows;
1. add standard R CMD check workflow
2. build pgkdown website

As these two workflows do the same work Travis and appveyor did, we can remove the yaml files related to both.

For more package improvements as mentioned in #100, we can do it in a separate branch/PR later.

### CODE REVIEW

**Comment by damianooldoni** [comment]
I set @hansvancalster as reviewer. However any other one with experience with GitHub actions can get a look :+1:

**Comment by damianooldoni** [comment]
Travis CI and appveyor should be removed or at least suspended via Settings -> Integrations
I have no rights to do it.

**Review by hansvancalster — APPROVED** [review]
Looks good 👍  I have no experience with GHA, but I see the GHA tests have run (with one failing on Windows),, so I believe this is OK.

**Comment by hansvancalster** [comment]
> Travis CI and appveyor should be removed or at least suspended via Settings -> Integrations
> I have no rights to do it.

I don't see the settings tab either. @peterdesmet can you change this? Or give me the rights to do so?

**Comment by hansvancalster** [comment]
The failing test on Windows is due to this warning:
image

I can reproduce the warning on my machine (but don't remember having seen this on my previous laptop with Windows 7). It runs fine on the other OS.

**Comment by peterdesmet** [comment]
@hansvancalster all of BMK now has admin rights and I have removed personalized (non-team) access for BMK members.

**Comment by damianooldoni** [comment]
Indeed, as @hansvancalster noticed on https://github.com/inbo/inborutils/pull/101#issuecomment-792534650, this is something typical of Windows. I get the same warning on my macine which runs Win  7. I can give a look, but everyone is welcome to give a try. I am not an expert in encoding stuff.

**Comment by hansvancalster** [comment]
@damianooldoni I have deleted the travis and appveyor webhooks (settings -> webhooks) and changed the branch protection rules so that all GHA checks are required and the travis checks are disabled (settings -> branches).

**Comment by damianooldoni** [comment]
thanks @hansvancalster. Indeed, Travis disappeared from the checks window. We have now only to solve the warning on Windows machine about the encoding of `\u00B0` (degree sign) in `read_mow_data.R`.

**Comment by hansvancalster** [comment]
Yeay success! All checks passed. Thank you @damianooldoni for making this happen 🚀 👍

**Pull request merged**
