### PR TITLE
Review gert fbquery

### PR DESCRIPTION
**Pull request by hansvancalster**
This PR makes some improvements to the `florabank_observations()` function. Thanks to @gertvanspaendonk.

### CODE REVIEW

**Review by ElsLommelen — COMMENTED** [review]
One general remark: wouldn't it be more straightforward to let the user give one vector with species names (scientific and/or dutch)?  This would make the code shorter (no need for 4 different options) and it is moreover easier for users.

And some small remarks on the examples in the documentation of florabank_observations:
- ó of scientific name is compiled as Ã³ -> Dactmacu1 has 0 rows and is not equal to Dactmacu2 and Dactmacu3
- a small explanation of 'not run' could be helpful.  (E.g. something like: 'code can only be run if connecting to the database is possible')

**Comment by hansvancalster** [comment]
Thanks for spotting the problems in the Rd file. They are solved. Regarding your general remark: I prefer to keep it as is, because being able to query with partial matching is an important use case next to being able to query for observations of multiple species without partial matching. The former requires the sql `LIKE` statement, while the latter requires the sql `IN` statement. Unfortunately, it is not straightforward (not possible?) to combine the functionality of `LIKE` and `IN`. That would have been my preferred way to write the query, so that the function could just have an argument `partial_matching` TRUE or FALSE.

**Review by ElsLommelen — APPROVED** [review]
For clarity, the issue that I was pinpointing at, is the fact that there are 2 parameters: 'scient_name' and 'dutch_name'.  If they would be replaced by one parameter 'name' or 'species_name' (in which both scientific and dutch names can be entered), one does not need to test all combinations of these 2 variables, but only the different statuses of the one variable.  (And queries simply need to test the presence of the names in 2 columns instead of 1.)

The disadvantage is indeed that a user, while using wildcards, only can enter 1 record at the time instead of 2, but what is the chance that he has exactly 1 dutch and 1 scientific name (to take advantage of the fact that he can enter 2 variables)?

I also had a quick look at possibilities to add multiple strings with wildcards. As tblTaxon is not full-text indexed (and contains cannot be used), there is indeed no straightforward method to use like with a vector.  The most convenient way seems to add `WHERE xxx LIKE '%bla%' OR xxx LIKE '%foo' OR ...`, a string that could easily be composed in R.  To fasten the query, it might be useful to filter the strings without wildcards and group them in a first where-statement: ` WHERE xxx IN ('string1', 'string2',...) AND xxx LIKE '%bla%' OR xxx LIKE '%foo' OR ...`

I leave it up to you to decide whether or not to add (one of) these suggestions.

**Comment by hansvancalster** [comment]
@ElsLommelen excellent suggestions!! Can you have a look at 6e1a895?

**Comment by ElsLommelen** [comment]
Perfect!  (Ready to merge in my opinion, but I already approved and I can't do it twice, I think.)

**Pull request merged**
