### PR TITLE
 connect_inbo_dbase(): cross-platform use

### PR DESCRIPTION
**Pull request by florisvdh**
A tweak was added that makes the `sql_driver` argument obsolete: the SQL driver is now set automatically both for "unix" and "windows" platforms.

The reason is that having a different implementation between OSes seems to me as an obstacle for platform-independent R-scripts.

Please test it, I've only tested it on Linux.

### CODE REVIEW

**Comment by stijnvanhoey** [comment]
Interesting! Is there a possibility I do have 2 drivers installed and I would want to specify which one I am using? This would still require the optional argument to specify the driver myself.

**Comment by florisvdh** [comment]
That seems a more special case which may make it still worth to provide the argument. Well, then a default argument `sql_driver = NA` seems a reasonable solution to me. If it's `NA`, use the proposed code, if it is set, use the user's setting. Like that?

But I think in a normal situation you will not have two versions of SQL driver installed in Linux? The driver is provided by the `msodbcsql` package and its version determines which driver you have installed.

**Comment by stijnvanhoey** [comment]
well... the thing is:

```
> odbcListDrivers() %>% filter(attribute == "Driver", stringr::str_detect(name, "SQL Server"))
                           name attribute                                                      value
1 ODBC Driver 11 for SQL Server    Driver /opt/microsoft/msodbcsql/lib64/libmsodbcsql-11.0.so.2270.0
2 ODBC Driver 13 for SQL Server    Driver    /opt/microsoft/msodbcsql/lib64/libmsodbcsql-13.1.so.9.1
3 ODBC Driver 17 for SQL Server    Driver    /opt/microsoft/msodbcsql/lib64/libmsodbcsql-17.0.so.1.1
```
;-( probably my issue...

**Comment by florisvdh** [comment]
I guess so... :-) You could solve it in some way like I suggested, but I do encourage maximal portability between platforms. Feel free to add your further tweaking.

For the automated handling in your case, a further sorting of the driver vector so that the highest version is picked, could be worthwile as well.

Just being curious: are there interesting differences between the drivers you installed? The [INBO tutorial](https://inbo.github.io/tutorials/installation/user/user_install_kerberos/) still lists version 13 so that's the one I have (and set fixed).

**Comment by stijnvanhoey** [comment]
I just try to be updated on the driver and more recent drivers sometimes support more options, @Jo-Loos is actually the specialist on this and could help you with it.

**Comment by stijnvanhoey** [comment]
Thanks Floris, I checked the setup and it also works in y situation. merging

**Pull request merged**
