### PR TITLE
Deprecated

### PR DESCRIPTION
**Pull request by hansvancalster**
This PR changes the .Deprecated functions to .Defunct functions (which signal an error and point to the replacing functions in `inbodb`.

### CODE REVIEW

**Comment by hansvancalster** [comment]
@damianooldoni or @niconoe when I run R CMD check, the tests for `setup_codingclub_session` fail:

image

Can  one of you have a look?

**Comment by niconoe** [comment]
Hi @damianooldoni, I just had a quick look but I was wondering if we shouldn't be a bit more lax with those tests and use [changedFiles](https://rdrr.io/r/utils/changedFiles.html) so we have a more granular file snapshot comparison method (for example to only count files rather than check creation dates, ...) than what `expect_identical()` provides.

**Comment by ElsLommelen** [comment]
@niconoe What happens if we actually remove these files in some years?  (We moved the functions to inbodb about a year ago, so we are gradually discouraging to use them here...)
As inborutils has a collection of unrelated functions, this movement of functions to (newly started) more dedicated packages is likely to happen now and then.

**Review by ElsLommelen — CHANGES_REQUESTED** [review]
I added a PR with some suggestions to replace deprecated by defunct in the documentation as well (and added a reference to the inbodb website in it).  Please have a look at it.  The code itself is fine.

**Review by ElsLommelen — APPROVED** [review]

**Comment by damianooldoni** [comment]
The required Travis CI PR check is blocked due to negative credit balance. See https://travis-ci.com/github/inbo/inborutils

Travis CI became greedy :disappointed:

**Comment by damianooldoni** [comment]
If this PR is really ready to merge, I will pull it in branch [add-gitHub-actions-for-tests](https://github.com/inbo/inborutils/tree/add-gitHub-actions-for-tests). Otherwise some tests will fail and so the automatically run test will fail as they were failing here before being solved by #99.

**Comment by ElsLommelen** [comment]
For me it seems ready to merge, but please wait for @hansvancalster to confirm.

**Comment by hansvancalster** [comment]
Yes it is ok. There was just one warning and one note but no errors.

Op vr 5 mrt. 2021 18:28 schreef ElsLommelen <notifications@github.com>:

**Comment by hansvancalster** [comment]
This branch was moved to PR #101. Closing this one.

**Pull request closed without merging**
